# Generated by Django 3.2.5 on 2021-07-31 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleExposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_asignado', models.CharField(max_length=100)),
                ('exposicion_asignada', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('codigo_validacion', models.CharField(max_length=100)),
                ('cuit', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('mail', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=100)),
                ('numero_sede', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_fin', models.DateField()),
                ('fecha_fin_replanificada', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_inicio_replanificada', models.DateField()),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('sede_asignada', models.IntegerField(null=True)),
                ('detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.detalleexposicion')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('caducidad', models.DateField()),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFinVigencia', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('montoAdicionalGuia', models.IntegerField()),
                ('nro_sede', models.IntegerField(null=True)),
                ('tipoDeEntrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.tipoentrada')),
                ('tipoVisita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.tipovisita')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fin', models.DateField(null=True)),
                ('fecha_inicio', models.DateField()),
                ('hora_fin', models.TimeField(null=True)),
                ('hora_inicio', models.TimeField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantMaximaVisitantes', models.IntegerField()),
                ('cantMaxPorGuia', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.empleado')),
                ('exposicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.exposicion')),
                ('tarifas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.tarifa')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadAlumnos', models.IntegerField()),
                ('cantidadAlumnosConfirmada', models.IntegerField()),
                ('duracionEstimada', models.IntegerField()),
                ('fechaHoraCreacion', models.DateTimeField()),
                ('fechaHoraReserva', models.DateTimeField()),
                ('horaFinReal', models.IntegerField()),
                ('horaInicioReal', models.IntegerField()),
                ('numeroReserva', models.IntegerField()),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('codigoSensor', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('duracionExtendida', models.IntegerField()),
                ('duracionResumida', models.IntegerField()),
                ('fechaCreacion', models.DateField()),
                ('fechaPrimerIngreso', models.DateField()),
                ('nombreObra', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('valuacion', models.CharField(max_length=100)),
                ('empleados', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateTimeField(null=True)),
                ('horaVenta', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.sede')),
                ('tarifa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.tarifa')),
            ],
        ),
        migrations.AddField(
            model_name='detalleexposicion',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rve.obra'),
        ),
    ]
