# Generated by Django 3.2.5 on 2021-07-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='numero_sede',
        ),
    ]
