# Generated by Django 3.2.5 on 2021-07-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rve', '0002_remove_empleado_numero_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='numero_sede',
            field=models.IntegerField(null=True),
        ),
    ]
